Numpy in Python


Numpy is a fundamental library for scinetific computing in python.It provides support for arrays and matrices along with a collection of mathematical functions to operate on these data structures


In [3]:
import numpy as np

## create array using numpy
##1d array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)  ## i row 5 column

array([[1, 2, 3, 4, 5]])

In [ ]:

## 2d array
arr3=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
## some common atrributes

arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("shape:",arr.shape)
print("Number of dimensions: ",arr.ndim)
print("Size (number of elements): ",arr.size)
print("data type : ",arr.dtype)
print("Item size (in bytes)",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
Number of dimensions:  2
Size (number of elements):  6
data type :  int64
Item size (in bytes) 8


In [14]:
## NUmpy vectorized opeartion

arr4=np.array([1,2,3,4,5])
arr5=np.array([10,20,30,40,50])

## element wise addition

print("Addition : ",arr4 + arr5)
print("substraction : ",arr4 - arr5)
print("Multiplication : ",arr4 * arr5)
print("Division : ",arr4 / arr5)

Addition :  [11 22 33 44 55]
substraction :  [ -9 -18 -27 -36 -45]
Multiplication :  [ 10  40  90 160 250]
Division :  [0.1 0.1 0.1 0.1 0.1]


In [18]:
# logical opeartions
data=np.array([1,2,3,4,5,6,7,8,9,10,11,15])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])